name: Stream
channels:
  - anaconda
  - defaults
  - pip:
      - gitdb==4.0.10
      - gitpython==3.1.29
      - keras==2.11.0
      - packaging==21.3
      - pandas==1.5.2
      - pillow==9.3.0
      - pyarrow==10.0.1
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pydeck==0.8.0
      - pygments==2.13.0
      - pympler==1.0.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.2
      - python-dateutil==2.8.2
      - streamlit==1.15.2
      - tensorboard==2.11.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-intel==2.11.0
      - tensorflow-io-gcs-filesystem==0.28.0
